### PR TITLE
Add SnowRealMagic compatibility

### PR DESCRIPTION
**Pull request by aedans**
Snow real magic places snow on grass and flowers. Snow under trees places snow under trees. This pull request places snow on grass and flowers under trees.

### CODE REVIEW

**Comment by bl4ckscor3** [comment]
I'm not a fan of doing this with reflection. There should be a check for whether snow real magic is loaded, then call the class of the mod directly to set the consumer without the use of reflection.

And does snow real magic place snow on grass and flowers when it's snowing? If so, that should be added here as well to work under trees.

**Comment by aedans** [comment]
I'll take a look at that later today--I've been using Java forever but I'm still pretty new to modding, so some of my code might not be idiomatic--and I'll implement placing snow under trees while snowing while I'm at it.

**Comment by aedans** [comment]
Work's been keeping me busy but I found some time to remove the reflection and implement snowing on plants under trees.

**Comment by bl4ckscor3** [comment]
That looks better! Thank you very much!

**Pull request merged**
